### ISSUE TITLE
Release main scripts

### ISSUE THREAD

**Issue by quqixun** [kristijanbartol/general-3d-humans#1]
When will you release main scripts for training, inference, and evaluation ?

**Comment by kristijanbartol** [comment]
Thank you for pinging me about it, I was postponing it for too long. I will do it by the end of the week (tomorrow), there isn't much work to do.

Hi @quqixun , I updated and verified the `src/learn_pose.py` script. I tried to train and evaluate the model using the arguments provided in an updated README.md. I will have more updates by the end of the week, but now training and evaluation should work. Please note that this is my first standalone repository, so I will probably need a few more iterations to make it more intuitive for other users. Feel free to reach out for any issues with training/evaluation!

P.S. I expect to add the following by the end of the week:
- [x] update documentation for the remaining functions (not complete, but mostly done)
- [X] make train/eval run from `main.py`, without descending into `./src/`.
- [x] simplify command line arguments
- [x] in general, improve the readability
- [x] inference based on provided 2D keypoints and camera parameters

The inference based on previously extracted 2D keypoints and known camera parameters will be supported this week. It would be very useful to also support inference directly from images, as well as using unknown camera parameters - I will have to do it next week (see #2 ).

Update: I'm sorry, I will have to postpone the inference completely for next week.

Update: DONE.
